### PR TITLE
PR for SLURM Singularity backend support

### PR DESCRIPTION
**Pull request by paulstretenowich**
@sitag 
Here is the PR. Tell me what you think about it.

### CODE REVIEW

**Comment by sitag** [comment]
@paulstretenowich Can you log what tests you ran? Did you also test in Local mode? Did the md5s match with sambamba?

**Comment by paulstretenowich** [comment]
I tested on standard tests and on the IHEC tests (h3k27me3 still running). I can test In Local mode but I haven't yet. Yes, with sambamba the md5s matched for h3k4me3 IHEC test.

**Comment by paulstretenowich** [comment]
@sitag 
It worked with h3k27me3 IHEC test too.
The Local test using `singularity_encode_test_tasks.sh` worked. Do you need me to test Local with IHEC testsets? I don't think it's needed because it worked before, what I modified doesn't impact the Local mode usage  and it worked on the `singularity_encode_test_tasks.sh` test using Local.

**Comment by sitag** [comment]
I merged this... checking Local now.

**Pull request merged**
